#ifndef QT5_VIRTUALKEYBOARD_LIBRARY_GLOBAL_H
#define QT5_VIRTUALKEYBOARD_LIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QT5_VIRTUALKEYBOARD_LIBRARY_LIBRARY)
#  define QT5_VIRTUALKEYBOARD_LIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QT5_VIRTUALKEYBOARD_LIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QT5_VIRTUALKEYBOARD_LIBRARY_GLOBAL_H
